default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bankruptcy_admin_development

test:
  <<: *default
  database: bankruptcy_admin_test

production:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: db
  port: 5432
